<?php

namespace Mrzard\OpenExchangeRatesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExchangeRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeRateRepository extends EntityRepository
{

    public function getExchangeRateForCurrency($currency)
    {
        $query = $this->createQueryBuilder('c')
                ->where('c.currency = :currency')
                ->setParameter('currency', $currency)
                ->setMaxResults(1);

        return $query->getQuery()
                        ->useResultCache(true, 86400, 'exchangeRate' . $currency)
                        ->getOneOrNullResult();
    }

}