<?php

namespace Mrzard\OpenExchangeRatesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExchangeRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExchangeRateRepository extends EntityRepository
{
}
